export { typeBuilderWithFactories } from "./type/builder-lowering.ts"
export {
  array,
  arrayItem,
  custom,
  enum_ as enum,
  enum_,
  field,
  isAuthoredUnitValueType,
  isUnitValueType,
  lazy,
  literal,
  literalValues,
  option,
  optional,
  optionItem,
  result,
  struct,
  structFieldOptions,
  structFields,
  structFieldWireType,
  sum,
  unit,
} from "./type/constructors.ts"
export type {
  AnyValueType,
  ArrayValueType,
  BigIntValueType,
  BoolValueType,
  BytesValueType,
  Encoded,
  EncodedOf,
  F32ValueType,
  F64ValueType,
  I8ValueType,
  I16ValueType,
  I32ValueType,
  I64ValueType,
  I128ValueType,
  I256ValueType,
  LazyValueType,
  LiteralValueType,
  NumberValueType,
  OptionValueType,
  ResultValueType,
  StdbValueType,
  StringValueType,
  StructFieldOptions,
  StructFields,
  StructFieldsOf,
  StructFieldType,
  StructLikeValueType,
  StructValueType,
  SumValueType,
  SumVariants,
  Type,
  TypeKind,
  TypeOf,
  U8ValueType,
  U16ValueType,
  U32ValueType,
  U64ValueType,
  U128ValueType,
  U256ValueType,
  UnitValueType,
  ValueCodec,
  ValueType,
  ValueTypeInfo,
} from "./type/core.ts"
export {
  annotateValueTypeSchema,
  applyFieldOptions,
  fieldOptionsObject,
  StdbValueCodecError,
  tableFieldOptions,
} from "./type/core.ts"
export {
  contentAddressedSatsTypeBuilder,
  satsTypeFingerprint,
} from "./type/fingerprint.ts"
export {
  attachStdbType,
  supportsAutoInc,
  supportsColumnDefault,
  supportsColumnName,
  supportsPrimaryKey,
  typeInfo,
} from "./type/metadata.ts"
export {
  namedValueType,
  StdbTypeNotNameableError,
} from "./type/core.ts"
export {
  ReservedSatsTypeIdentifierPattern,
  SatsTypeIdentifierPattern,
  StdbTypeIdentifierError,
  validateSatsTypeIdentifier,
} from "./sats-identifier-validation.ts"
export {
  bigint,
  bool,
  bytes,
  connectionId,
  f32,
  f64,
  i8,
  i16,
  i32,
  i64,
  i128,
  i256,
  identity,
  scheduleAt,
  string,
  timeDuration,
  timestamp,
  u8,
  u16,
  u32,
  u64,
  u128,
  u256,
  uuid,
} from "./type/primitives.ts"
export { dbCodec, httpCodec, wsCodec } from "./type/representation-codec.ts"
export type {
  OptionalKeys,
  OptionalStructField,
  OptionWire,
  RequiredKeys,
  ResultType,
  ResultWire,
  ResultWireVariant,
  StructType,
  SumType,
  SumVariant,
  SumWire,
  SumWireVariant,
  UnitWire,
} from "./type/shapes.ts"
