export {
  type AnonymousViewDecl,
  type AnyBuilderImpl,
  type AnyCallableDecl,
  type AnyEndpointDecl,
  type AnyHttpRouteDecl,
  type AnyStdbModule,
  type ArgsFor,
  type DeclNameOf,
  type DeclOf,
  type DeclSpecOf,
  type DeclSpecRecordOfGroup,
  type EndpointsOfGroup,
  type ErrorsOfGroup,
  declOf,
  type ErrorsFor,
  type GroupCheckedHandlers,
  type GroupEndpointPairsOf,
  type GroupEndpointPairsOfModule,
  type GroupHandlersRecord,
  type GroupImpl,
  GroupImplTypeId,
  type GroupNameOf,
  type GroupNames,
  type HandlerFor,
  type HandlerForKey,
  type HandlersOf,
  type HttpHandlerArgsFor,
  type HttpHandlerErrorsFor,
  type HttpHandlerSuccessFor,
  type LifecycleConfig,
  type LifecycleConfigEntry,
  type LifecycleDecl,
  type LifecycleImpl,
  LifecycleImplTypeId,
  type LifecycleOf,
  type ModuleBrand,
  type ModuleBrandTypeId,
  type ModuleSpecFor,
  type ProcedureArgsFor,
  type ProcedureDecl,
  type ProcedureErrorsFor,
  type ProcedureSuccessFor,
  type RawHttpRouteDecl,
  type ReducerArgsFor,
  type ReducerDecl,
  type ReducerErrorsFor,
  type ReducerSuccessFor,
  type RowOf,
  type ScheduledProcedureDecl,
  type ScheduledProcedureSpec,
  type ScheduledReducerDecl,
  type ScheduledReducerSpec,
  type ScheduledTableNameOf,
  type SchedulePairsOf,
  type SenderViewDecl,
  type SpecOfModule,
  StdbBuilder,
  StdbFn,
  StdbGroup,
  StdbHttp,
  StdbHttpGroup,
  StdbModule,
  moduleExports,
  type ModuleAccessors,
  type ModuleExports,
  type SuccessFor,
  type TablesFromTuple,
  type TypedHttpRouteDecl,
  type ViewArgsFor,
  type ViewErrorsFor,
  type ViewSuccessFor,
  wireNameForDecl,
  wireNameOf,
} from "./builder.ts"
export type { CallFailure, RawCallFailure } from "./client/call-errors.ts"
export type { ResultValuesOf } from "./client/result-values.ts"
export {
  identityEquals,
  IdentityFormatError,
  type IdentityHex,
  normalizeIdentity,
} from "./identity.ts"
export {
  catchRawTags,
  DomainCallError,
  encodeCallArgs,
  RemoteRejectedBody,
  RemoteRejectedError,
  TransportError,
} from "./client/call-errors.ts"
export {
  httpApiBaseUrl,
  type ProjectedHttpApi,
  StdbHttpProjectionError,
  toHttpApi,
} from "./client/http-api.ts"
export type {
  ProjectedHttpClientTag,
  ProjectedHttpClientTagIdentifier,
  GroupIdsOf,
  ProjectedHttpGroupClient,
  SessionOf,
  WsSessionTag,
  WsSessionTagIdentifier,
} from "./client/index.ts"
export {
  type EventTableStreamBufferOptions,
  EventTableStreamOverflowError,
  TableStreamOverflowError,
  type SessionStreamBufferOptions,
} from "./client/session-stream.ts"
export {
  WsConnectError,
  WsConnectTimeoutError,
} from "./client/ws-resource.ts"
export type { SubscriptionFailure } from "./client/ws-subscription.ts"
export {
  type HttpHandlerReflection,
  type LifecycleReflection,
  type ModuleReflection,
  type ProcedureReflection,
  type ReducerReflection,
  type ReflectCallbacks,
  reflect,
  type TableReflection,
  type ViewReflection,
} from "./reflect.ts"
export {
  type ConstraintSpec,
  type UniqueConstraintSpec,
  unique,
} from "./contract/constraint.ts"
export {
  type AnyErrorDefinition,
  type DefinitionOfInput,
  type DefinitionOfInputOrUndefined,
  type ErrorDefinition,
  type ErrorInstances,
  type ErrorSpec,
  type ErrorsInput,
  type ErrorTags,
  declaredErrorGuard,
  error,
  errors,
  type NamespacedErrorDefinition,
} from "./contract/error.ts"
export {
  type AnyFieldType,
  type FieldOptions,
  type FieldOptionsOf,
  type FieldType,
  type FieldValue,
} from "./contract/field.ts"
export {
  type HttpHandlerMethod,
  type HttpHandlerSpec,
  type RawHttpHandlerSpec,
  type TypedHttpHandlerSpec,
} from "./contract/http-handler.ts"
export {
  type LifecycleName,
  type LifecycleSpec,
  type LifecycleSpecs,
} from "./contract/lifecycle.ts"
export { type AnyModuleSpec, type ModuleSpec } from "./contract/module.ts"
export {
  assertValid,
  formatModuleDiagnostics,
  RESERVED_GROUP_CLIENT_KEYS,
  StdbDiagnostic,
  type StdbDiagnosticCode,
  type StdbDiagnosticSeverity,
  StdbValidationError,
  validate,
} from "./contract/module-validation.ts"
export { type ProcedureSpec } from "./contract/procedure.ts"
export { type ReducerSpec } from "./contract/reducer.ts"
export * as ScheduleAt from "./contract/schedule-at.ts"
export { type ModuleSettings } from "./contract/settings.ts"
export {
  type AnyScheduledTableSpec,
  type AnyTableSpec,
  rowType,
  scheduledTable,
  type TableRow,
  type TableSpec,
  table,
} from "./contract/table.ts"
export {
  type IndexAlgorithm,
  type IndexSpec,
  index,
} from "./contract/table-index.ts"
export {
  type ColumnKey,
  type PrimaryKeyNames,
  type SinglePrimaryKeyName,
  type SinglePrimaryKeyValue,
} from "./contract/table-keys.ts"
export {
  describe,
  type StdbTypeDescriptor,
} from "./contract/type/descriptor.ts"
export { StdbHostEncodeError } from "./contract/type/host-codec.ts"
export type {
  AnyValueType,
  ArrayValueType,
  BigIntValueType,
  BoolValueType,
  BytesValueType,
  Encoded,
  EncodedOf,
  F32ValueType,
  F64ValueType,
  I8ValueType,
  I16ValueType,
  I32ValueType,
  I64ValueType,
  I128ValueType,
  I256ValueType,
  LazyValueType,
  LiteralValueType,
  NumberValueType,
  OptionalKeys,
  OptionalStructField,
  OptionValueType,
  OptionWire,
  RequiredKeys,
  ResultType,
  ResultValueType,
  ResultWire,
  ResultWireVariant,
  StdbValueType,
  StringValueType,
  StructFieldOptions,
  StructFields,
  StructFieldsOf,
  StructFieldType,
  StructLikeValueType,
  StructType,
  StructValueType,
  SumType,
  SumValueType,
  SumVariant,
  SumVariants,
  SumWire,
  SumWireVariant,
  Type,
  TypeKind,
  TypeOf,
  U8ValueType,
  U16ValueType,
  U32ValueType,
  U64ValueType,
  U128ValueType,
  U256ValueType,
  UnitValueType,
  UnitWire,
  ValueCodec,
  ValueType,
  ValueTypeInfo,
} from "./contract/type.ts"
export {
  array,
  bigint,
  bool,
  bytes,
  connectionId,
  custom,
  dbCodec,
  enum_ as enum,
  enum_ as enumType,
  f32,
  f64,
  httpCodec,
  i8,
  i16,
  i32,
  i64,
  i128,
  i256,
  identity,
  isUnitValueType,
  lazy,
  literal,
  option,
  optional,
  result,
  StdbTypeIdentifierError,
  StdbTypeNotNameableError,
  StdbValueCodecError,
  scheduleAt,
  string,
  struct,
  sum,
  timeDuration,
  timestamp,
  u8,
  u16,
  u32,
  u64,
  u128,
  u256,
  unit,
  uuid,
  wsCodec,
} from "./contract/type.ts"
export {
  type AnyViewSpec,
  type ViewSpec,
} from "./contract/view.ts"
export { StdbDecodeError } from "./decode-error.ts"
export { Headers, Request, Router, SyncResponse } from "./http-primitives.ts"
export { type ModuleProject, project } from "./project.ts"
export type {
  ReducerAsyncNotAllowedError,
  ReducerGlobalRandomNotAllowedError,
  ReducerWallClockNotAllowedError,
  StdbAutoIncOverflowError,
  StdbHostCallError,
  StdbHostFailure,
  StdbNoSuchRowError,
  StdbScheduleDelayTooLongError,
  StdbSenderFailure,
  StdbUniqueAlreadyExistsError,
} from "./server/services.ts"
export {
  compareTimestampAsc,
  compareTimestampDesc,
  timestampAddMillis,
  timestampIsDue,
  timestampToDate,
  timestampToIso,
  timestampToMillis,
} from "./timestamp.ts"

const effectSpacetimeDbEntrypoint = "effect-spacetimedb" as const
void effectSpacetimeDbEntrypoint
