// Generated by effect-spacetimedb codegen (spacetime 2.10.1, esbuild 0.25.12). DO NOT EDIT.
// index.ts
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  table as __table
} from "spacetimedb";

// constraint_entry_insert_reducer.ts
import {
  t as __t
} from "spacetimedb";
var constraint_entry_insert_reducer_default = {
  id: __t.string(),
  slug: __t.string(),
  tenantId: __t.string(),
  email: __t.string(),
  note: __t.string()
};

// constraint_entry_update_reducer.ts
import {
  t as __t2
} from "spacetimedb";
var constraint_entry_update_reducer_default = {
  id: __t2.string(),
  slug: __t2.string(),
  tenantId: __t2.string(),
  email: __t2.string(),
  note: __t2.string()
};

// emit_presence_reducer.ts
import {
  t as __t4
} from "spacetimedb";

// types.ts
import {
  t as __t3
} from "spacetimedb";
var AllThings = __t3.object("AllThings", {});
var AllUsers = __t3.object("AllUsers", {});
var AllUsersQuery = __t3.object("AllUsersQuery", {});
var AuditLog = __t3.object("AuditLog", {
  id: __t3.u64(),
  get kind() {
    return EffectSpacetimeDbEnum1534687482507768812807638219320528948671;
  },
  subject: __t3.string()
});
var ConstraintEntry = __t3.object("ConstraintEntry", {
  id: __t3.string(),
  slug: __t3.string(),
  tenantId: __t3.string(),
  email: __t3.string(),
  note: __t3.string()
});
var EffectSpacetimeDbEnum0031112371198784746010532026326169871055 = __t3.enum("EffectSpacetimeDbEnum0031112371198784746010532026326169871055", {
  Reducer: __t3.unit(),
  Procedure: __t3.unit()
});
var EffectSpacetimeDbEnum0077559484257204371700884911820393236990 = __t3.enum("EffectSpacetimeDbEnum0077559484257204371700884911820393236990", {
  Joined: __t3.unit(),
  Left: __t3.unit()
});
var EffectSpacetimeDbEnum1534687482507768812807638219320528948671 = __t3.enum("EffectSpacetimeDbEnum1534687482507768812807638219320528948671", {
  Init: __t3.unit(),
  Connected: __t3.unit(),
  Disconnected: __t3.unit()
});
var MembershipView = __t3.object("MembershipView", {
  tenantId: __t3.string(),
  email: __t3.string(),
  note: __t3.string()
});
var NativeRangeEntry = __t3.object("NativeRangeEntry", {
  id: __t3.u64(),
  owner: __t3.identity(),
  happenedAt: __t3.timestamp(),
  label: __t3.string()
});
var OptionalRangeEntry = __t3.object("OptionalRangeEntry", {
  id: __t3.u64(),
  rank: __t3.option(__t3.u64()),
  label: __t3.string()
});
var PresenceEvent = __t3.object("PresenceEvent", {
  userId: __t3.string(),
  get kind() {
    return EffectSpacetimeDbEnum0077559484257204371700884911820393236990;
  }
});
var PrivateAuditLog = __t3.object("PrivateAuditLog", {});
var ProcedureSchedule = __t3.object("ProcedureSchedule", {
  scheduledId: __t3.u64(),
  scheduledAt: __t3.scheduleAt(),
  note: __t3.string()
});
var ReducerSchedule = __t3.object("ReducerSchedule", {
  scheduledId: __t3.u64(),
  scheduledAt: __t3.scheduleAt(),
  note: __t3.string()
});
var ScheduledResult = __t3.object("ScheduledResult", {
  id: __t3.u64(),
  get target() {
    return EffectSpacetimeDbEnum0031112371198784746010532026326169871055;
  },
  note: __t3.string(),
  sender: __t3.string(),
  identity: __t3.string(),
  databaseIdentity: __t3.string()
});
var SelfUser = __t3.object("SelfUser", {});
var Thing = __t3.object("Thing", {
  id: __t3.string(),
  label: __t3.string(),
  count: __t3.u64()
});
var UniqueMembership = __t3.object("UniqueMembership", {
  tenantId: __t3.string(),
  email: __t3.string(),
  note: __t3.string()
});
var User = __t3.object("User", {
  id: __t3.string(),
  name: __t3.string()
});

// emit_presence_reducer.ts
var emit_presence_reducer_default = {
  userId: __t4.string(),
  get kind() {
    return EffectSpacetimeDbEnum0077559484257204371700884911820393236990;
  }
};

// membership_insert_strict_reducer.ts
import {
  t as __t5
} from "spacetimedb";
var membership_insert_strict_reducer_default = {
  tenantId: __t5.string(),
  email: __t5.string(),
  note: __t5.string()
};

// membership_upsert_reducer.ts
import {
  t as __t6
} from "spacetimedb";
var membership_upsert_reducer_default = {
  tenantId: __t6.string(),
  email: __t6.string(),
  note: __t6.string()
};

// native_range_clear_reducer.ts
var native_range_clear_reducer_default = {};

// native_range_insert_reducer.ts
import {
  t as __t7
} from "spacetimedb";
var native_range_insert_reducer_default = {
  owner: __t7.identity(),
  happenedAt: __t7.timestamp(),
  label: __t7.string()
};

// optional_range_clear_reducer.ts
var optional_range_clear_reducer_default = {};

// optional_range_insert_reducer.ts
import {
  t as __t8
} from "spacetimedb";
var optional_range_insert_reducer_default = {
  rank: __t8.option(__t8.u64()),
  label: __t8.string()
};

// probe_async_reducer.ts
var probe_async_reducer_default = {};

// probe_random_reducer.ts
var probe_random_reducer_default = {};

// probe_wall_clock_reducer.ts
var probe_wall_clock_reducer_default = {};

// replace_scheduled_reducer_note_reducer.ts
import {
  t as __t9
} from "spacetimedb";
var replace_scheduled_reducer_note_reducer_default = {
  existingNote: __t9.string(),
  replacementNote: __t9.string()
};

// schedule_delete_candidate_reducer.ts
import {
  t as __t10
} from "spacetimedb";
var schedule_delete_candidate_reducer_default = {
  note: __t10.string()
};

// schedule_interval_reducer_note_reducer.ts
import {
  t as __t11
} from "spacetimedb";
var schedule_interval_reducer_note_reducer_default = {
  note: __t11.string()
};

// schedule_procedure_note_reducer.ts
import {
  t as __t12
} from "spacetimedb";
var schedule_procedure_note_reducer_default = {
  note: __t12.string()
};

// schedule_reducer_note_reducer.ts
import {
  t as __t13
} from "spacetimedb";
var schedule_reducer_note_reducer_default = {
  note: __t13.string()
};

// schedule_too_far_reducer.ts
import {
  t as __t14
} from "spacetimedb";
var schedule_too_far_reducer_default = {
  note: __t14.string()
};

// seed_self_user_reducer.ts
import {
  t as __t15
} from "spacetimedb";
var seed_self_user_reducer_default = {
  name: __t15.string()
};

// thing_clear_reducer.ts
var thing_clear_reducer_default = {};

// thing_delete_reducer.ts
import {
  t as __t16
} from "spacetimedb";
var thing_delete_reducer_default = {
  thingId: __t16.string()
};

// thing_force_update_reducer.ts
import {
  t as __t17
} from "spacetimedb";
var thing_force_update_reducer_default = {
  thingId: __t17.string(),
  label: __t17.string(),
  count: __t17.u64()
};

// thing_insert_then_abort_reducer.ts
import {
  t as __t18
} from "spacetimedb";
var thing_insert_then_abort_reducer_default = {
  thingId: __t18.string(),
  label: __t18.string(),
  count: __t18.u64()
};

// thing_insert_twice_atomic_reducer.ts
import {
  t as __t19
} from "spacetimedb";
var thing_insert_twice_atomic_reducer_default = {
  firstThingId: __t19.string(),
  firstLabel: __t19.string(),
  firstCount: __t19.u64(),
  secondThingId: __t19.string(),
  secondLabel: __t19.string(),
  secondCount: __t19.u64()
};

// thing_insert_twice_then_abort_reducer.ts
import {
  t as __t20
} from "spacetimedb";
var thing_insert_twice_then_abort_reducer_default = {
  firstThingId: __t20.string(),
  firstLabel: __t20.string(),
  firstCount: __t20.u64(),
  secondThingId: __t20.string(),
  secondLabel: __t20.string(),
  secondCount: __t20.u64()
};

// thing_noop_reducer.ts
var thing_noop_reducer_default = {};

// thing_panic_reducer.ts
var thing_panic_reducer_default = {};

// thing_set_reducer.ts
import {
  t as __t21
} from "spacetimedb";
var thing_set_reducer_default = {
  thingId: __t21.string(),
  label: __t21.string(),
  count: __t21.u64()
};

// user_require_reducer.ts
import {
  t as __t22
} from "spacetimedb";
var user_require_reducer_default = {
  userId: __t22.string()
};

// user_upsert_reducer.ts
import {
  t as __t23
} from "spacetimedb";
var user_upsert_reducer_default = {
  userId: __t23.string(),
  name: __t23.string()
};

// constraint_entry_conflict_then_commit_procedure.ts
import {
  t as __t24
} from "spacetimedb";
var params = {
  id: __t24.string(),
  slug: __t24.string(),
  tenantId: __t24.string(),
  email: __t24.string(),
  note: __t24.string(),
  markerThingId: __t24.string(),
  markerLabel: __t24.string(),
  markerCount: __t24.u64()
};
var returnType = __t24.unit();

// constraint_entry_get_procedure.ts
import {
  t as __t25
} from "spacetimedb";
var params2 = {
  id: __t25.string()
};
var returnType2 = __t25.option(ConstraintEntry);

// membership_by_tenant_email_range_procedure.ts
import {
  t as __t26
} from "spacetimedb";
var params3 = {
  tenantId: __t26.string(),
  emailLo: __t26.string(),
  emailHi: __t26.string()
};
var returnType3 = __t26.array(MembershipView);

// membership_get_procedure.ts
import {
  t as __t27
} from "spacetimedb";
var params4 = {
  tenantId: __t27.string(),
  email: __t27.string()
};
var returnType4 = __t27.option(MembershipView);

// native_range_by_owner_procedure.ts
import {
  t as __t28
} from "spacetimedb";
var params5 = {
  lo: __t28.identity(),
  hi: __t28.identity()
};
var returnType5 = __t28.array(__t28.string());

// native_range_by_timestamp_procedure.ts
import {
  t as __t29
} from "spacetimedb";
var params6 = {
  lo: __t29.timestamp(),
  hi: __t29.timestamp()
};
var returnType6 = __t29.array(__t29.string());

// optional_range_after_unset_procedure.ts
import {
  t as __t30
} from "spacetimedb";
var params7 = {};
var returnType7 = __t30.array(__t30.string());

// presence_event_count_procedure.ts
import {
  t as __t31
} from "spacetimedb";
var params8 = {};
var returnType8 = __t31.u64();

// thing_by_count_exact_procedure.ts
import {
  t as __t32
} from "spacetimedb";
var params9 = {
  count: __t32.u64()
};
var returnType9 = __t32.array(Thing);

// thing_by_count_range_procedure.ts
import {
  t as __t33
} from "spacetimedb";
var params10 = {
  lo: __t33.u64(),
  hi: __t33.u64()
};
var returnType10 = __t33.array(Thing);

// thing_by_count_range_exclusive_procedure.ts
import {
  t as __t34
} from "spacetimedb";
var params11 = {
  lo: __t34.u64(),
  hi: __t34.u64()
};
var returnType11 = __t34.array(Thing);

// thing_count_procedure.ts
import {
  t as __t35
} from "spacetimedb";
var params12 = {};
var returnType12 = __t35.u64();

// thing_get_procedure.ts
import {
  t as __t36
} from "spacetimedb";
var params13 = {
  thingId: __t36.string()
};
var returnType13 = __t36.option(Thing);

// thing_insert_in_tx_then_abort_procedure.ts
import {
  t as __t37
} from "spacetimedb";
var params14 = {
  thingId: __t37.string(),
  label: __t37.string(),
  count: __t37.u64()
};
var returnType14 = __t37.result(__t37.unit(), __t37.string());

// thing_insert_twice_in_tx_procedure.ts
import {
  t as __t38
} from "spacetimedb";
var params15 = {
  firstThingId: __t38.string(),
  firstLabel: __t38.string(),
  firstCount: __t38.u64(),
  secondThingId: __t38.string(),
  secondLabel: __t38.string(),
  secondCount: __t38.u64()
};
var returnType15 = __t38.unit();

// thing_list_procedure.ts
import {
  t as __t39
} from "spacetimedb";
var params16 = {};
var returnType16 = __t39.array(Thing);

// thing_outcome_procedure.ts
import {
  t as __t40
} from "spacetimedb";
var params17 = {
  thingId: __t40.string()
};
var returnType17 = __t40.result(Thing, __t40.string());

// user_get_procedure.ts
import {
  t as __t41
} from "spacetimedb";
var params18 = {
  userId: __t41.string()
};
var returnType18 = __t41.result(__t41.option(User), __t41.string());

// all_things_table.ts
import {
  t as __t42
} from "spacetimedb";
var all_things_table_default = __t42.row({
  id: __t42.string().primaryKey(),
  label: __t42.string(),
  count: __t42.u64()
});

// all_users_table.ts
import {
  t as __t43
} from "spacetimedb";
var all_users_table_default = __t43.row({
  id: __t43.string().primaryKey(),
  name: __t43.string()
});

// all_users_query_table.ts
import {
  t as __t44
} from "spacetimedb";
var all_users_query_table_default = __t44.row({
  id: __t44.string().primaryKey(),
  name: __t44.string()
});

// audit_log_table.ts
import {
  t as __t45
} from "spacetimedb";
var audit_log_table_default = __t45.row({
  id: __t45.u64().primaryKey(),
  get kind() {
    return EffectSpacetimeDbEnum1534687482507768812807638219320528948671;
  },
  subject: __t45.string()
});

// native_range_entry_table.ts
import {
  t as __t46
} from "spacetimedb";
var native_range_entry_table_default = __t46.row({
  id: __t46.u64().primaryKey(),
  owner: __t46.identity(),
  happenedAt: __t46.timestamp().name("happened_at"),
  label: __t46.string()
});

// presence_event_table.ts
import {
  t as __t47
} from "spacetimedb";
var presence_event_table_default = __t47.row({
  userId: __t47.string().name("user_id"),
  get kind() {
    return EffectSpacetimeDbEnum0077559484257204371700884911820393236990;
  }
});

// private_audit_log_table.ts
import {
  t as __t48
} from "spacetimedb";
var private_audit_log_table_default = __t48.row({
  id: __t48.string().primaryKey(),
  name: __t48.string()
});

// procedure_schedule_table.ts
import {
  t as __t49
} from "spacetimedb";
var procedure_schedule_table_default = __t49.row({
  scheduledId: __t49.u64().primaryKey().name("scheduled_id"),
  scheduledAt: __t49.scheduleAt().name("scheduled_at"),
  note: __t49.string()
});

// reducer_schedule_table.ts
import {
  t as __t50
} from "spacetimedb";
var reducer_schedule_table_default = __t50.row({
  scheduledId: __t50.u64().primaryKey().name("scheduled_id"),
  scheduledAt: __t50.scheduleAt().name("scheduled_at"),
  note: __t50.string()
});

// scheduled_result_table.ts
import {
  t as __t51
} from "spacetimedb";
var scheduled_result_table_default = __t51.row({
  id: __t51.u64().primaryKey(),
  get target() {
    return EffectSpacetimeDbEnum0031112371198784746010532026326169871055;
  },
  note: __t51.string(),
  sender: __t51.string(),
  identity: __t51.string(),
  databaseIdentity: __t51.string().name("database_identity")
});

// self_user_table.ts
import {
  t as __t52
} from "spacetimedb";
var self_user_table_default = __t52.row({
  id: __t52.string().primaryKey(),
  name: __t52.string()
});

// thing_table.ts
import {
  t as __t53
} from "spacetimedb";
var thing_table_default = __t53.row({
  id: __t53.string().primaryKey(),
  label: __t53.string(),
  count: __t53.u64()
});

// user_table.ts
import {
  t as __t54
} from "spacetimedb";
var user_table_default = __t54.row({
  id: __t54.string().primaryKey(),
  name: __t54.string()
});

// index.ts
var tablesSchema = __schema({
  auditLog: __table({
    name: "auditLog",
    indexes: [
      { accessor: "id", name: "auditLog_id_idx_btree", algorithm: "btree", columns: [
        "id"
      ] }
    ],
    constraints: [
      { name: "auditLog_id_key", constraint: "unique", columns: ["id"] }
    ]
  }, audit_log_table_default),
  nativeRangeEntry: __table({
    name: "nativeRangeEntry",
    indexes: [
      { accessor: "nativeRangeEntryHappenedAtIdx", name: "nativeRangeEntry_happened_at_idx_btree", algorithm: "btree", columns: [
        "happenedAt"
      ] },
      { accessor: "id", name: "nativeRangeEntry_id_idx_btree", algorithm: "btree", columns: [
        "id"
      ] },
      { accessor: "nativeRangeEntryOwnerIdx", name: "nativeRangeEntry_owner_idx_btree", algorithm: "btree", columns: [
        "owner"
      ] }
    ],
    constraints: [
      { name: "nativeRangeEntry_id_key", constraint: "unique", columns: ["id"] }
    ]
  }, native_range_entry_table_default),
  presenceEvent: __table({
    name: "presenceEvent",
    indexes: [],
    constraints: [],
    event: true
  }, presence_event_table_default),
  procedureSchedule: __table({
    name: "procedureSchedule",
    indexes: [
      { accessor: "scheduledId", name: "procedureSchedule_scheduled_id_idx_btree", algorithm: "btree", columns: [
        "scheduledId"
      ] }
    ],
    constraints: [
      { name: "procedureSchedule_scheduled_id_key", constraint: "unique", columns: ["scheduledId"] }
    ]
  }, procedure_schedule_table_default),
  reducerSchedule: __table({
    name: "reducerSchedule",
    indexes: [
      { accessor: "scheduledId", name: "reducerSchedule_scheduled_id_idx_btree", algorithm: "btree", columns: [
        "scheduledId"
      ] }
    ],
    constraints: [
      { name: "reducerSchedule_scheduled_id_key", constraint: "unique", columns: ["scheduledId"] }
    ]
  }, reducer_schedule_table_default),
  scheduledResult: __table({
    name: "scheduledResult",
    indexes: [
      { accessor: "id", name: "scheduledResult_id_idx_btree", algorithm: "btree", columns: [
        "id"
      ] }
    ],
    constraints: [
      { name: "scheduledResult_id_key", constraint: "unique", columns: ["id"] }
    ]
  }, scheduled_result_table_default),
  thing: __table({
    name: "thing",
    indexes: [
      { accessor: "thingCountIdx", name: "thing_count_idx_btree", algorithm: "btree", columns: [
        "count"
      ] },
      { accessor: "id", name: "thing_id_idx_btree", algorithm: "btree", columns: [
        "id"
      ] }
    ],
    constraints: [
      { name: "thing_id_key", constraint: "unique", columns: ["id"] }
    ]
  }, thing_table_default),
  user: __table({
    name: "user",
    indexes: [
      { accessor: "id", name: "user_id_idx_btree", algorithm: "btree", columns: [
        "id"
      ] }
    ],
    constraints: [
      { name: "user_id_key", constraint: "unique", columns: ["id"] }
    ]
  }, user_table_default),
  allThings: __table({
    name: "all_things",
    indexes: [],
    constraints: []
  }, all_things_table_default),
  allUsers: __table({
    name: "all_users",
    indexes: [],
    constraints: []
  }, all_users_table_default),
  allUsersQuery: __table({
    name: "all_users_query",
    indexes: [],
    constraints: []
  }, all_users_query_table_default),
  privateAuditLog: __table({
    name: "private_audit_log",
    indexes: [],
    constraints: []
  }, private_audit_log_table_default),
  selfUser: __table({
    name: "self_user",
    indexes: [],
    constraints: []
  }, self_user_table_default)
});
var reducersSchema = __reducers(
  __reducerSchema("constraint_entry_insert", constraint_entry_insert_reducer_default),
  __reducerSchema("constraint_entry_update", constraint_entry_update_reducer_default),
  __reducerSchema("emit_presence", emit_presence_reducer_default),
  __reducerSchema("membership_insert_strict", membership_insert_strict_reducer_default),
  __reducerSchema("membership_upsert", membership_upsert_reducer_default),
  __reducerSchema("native_range_clear", native_range_clear_reducer_default),
  __reducerSchema("native_range_insert", native_range_insert_reducer_default),
  __reducerSchema("optional_range_clear", optional_range_clear_reducer_default),
  __reducerSchema("optional_range_insert", optional_range_insert_reducer_default),
  __reducerSchema("probe_async", probe_async_reducer_default),
  __reducerSchema("probe_random", probe_random_reducer_default),
  __reducerSchema("probe_wall_clock", probe_wall_clock_reducer_default),
  __reducerSchema("replace_scheduled_reducer_note", replace_scheduled_reducer_note_reducer_default),
  __reducerSchema("schedule_delete_candidate", schedule_delete_candidate_reducer_default),
  __reducerSchema("schedule_interval_reducer_note", schedule_interval_reducer_note_reducer_default),
  __reducerSchema("schedule_procedure_note", schedule_procedure_note_reducer_default),
  __reducerSchema("schedule_reducer_note", schedule_reducer_note_reducer_default),
  __reducerSchema("schedule_too_far", schedule_too_far_reducer_default),
  __reducerSchema("seed_self_user", seed_self_user_reducer_default),
  __reducerSchema("thing_clear", thing_clear_reducer_default),
  __reducerSchema("thing_delete", thing_delete_reducer_default),
  __reducerSchema("thing_force_update", thing_force_update_reducer_default),
  __reducerSchema("thing_insert_then_abort", thing_insert_then_abort_reducer_default),
  __reducerSchema("thing_insert_twice_atomic", thing_insert_twice_atomic_reducer_default),
  __reducerSchema("thing_insert_twice_then_abort", thing_insert_twice_then_abort_reducer_default),
  __reducerSchema("thing_noop", thing_noop_reducer_default),
  __reducerSchema("thing_panic", thing_panic_reducer_default),
  __reducerSchema("thing_set", thing_set_reducer_default),
  __reducerSchema("user_require", user_require_reducer_default),
  __reducerSchema("user_upsert", user_upsert_reducer_default)
);
var proceduresSchema = __procedures(
  __procedureSchema("constraint_entry_conflict_then_commit", params, returnType),
  __procedureSchema("constraint_entry_get", params2, returnType2),
  __procedureSchema("membership_by_tenant_email_range", params3, returnType3),
  __procedureSchema("membership_get", params4, returnType4),
  __procedureSchema("native_range_by_owner", params5, returnType5),
  __procedureSchema("native_range_by_timestamp", params6, returnType6),
  __procedureSchema("optional_range_after_unset", params7, returnType7),
  __procedureSchema("presence_event_count", params8, returnType8),
  __procedureSchema("thing_by_count_exact", params9, returnType9),
  __procedureSchema("thing_by_count_range", params10, returnType10),
  __procedureSchema("thing_by_count_range_exclusive", params11, returnType11),
  __procedureSchema("thing_count", params12, returnType12),
  __procedureSchema("thing_get", params13, returnType13),
  __procedureSchema("thing_insert_in_tx_then_abort", params14, returnType14),
  __procedureSchema("thing_insert_twice_in_tx", params15, returnType15),
  __procedureSchema("thing_list", params16, returnType16),
  __procedureSchema("thing_outcome", params17, returnType17),
  __procedureSchema("user_get", params18, returnType18)
);
var REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.1"
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema
};
var tableAccessorAliases = {
  "all_things": "allThings",
  "all_users": "allUsers",
  "all_users_query": "allUsersQuery",
  "private_audit_log": "privateAuditLog",
  "self_user": "selfUser"
};
function __withTableAccessorAliases(target, freeze = false) {
  const out = Object.create(Object.getPrototypeOf(target));
  Object.defineProperties(out, Object.getOwnPropertyDescriptors(target));
  for (const [deprecatedAccessor, targetAccessor] of Object.entries(tableAccessorAliases)) {
    if (deprecatedAccessor in out) {
      continue;
    }
    Object.defineProperty(out, deprecatedAccessor, {
      enumerable: true,
      configurable: false,
      get: () => out[targetAccessor]
    });
  }
  return freeze ? Object.freeze(out) : out;
}
var tablesBase = __makeQueryBuilder(tablesSchema.schemaType);
var tables = __withTableAccessorAliases(tablesBase, true);
var reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);
var procedures = __convertToAccessorMap(proceduresSchema.procedures);
var SubscriptionBuilder = class extends __SubscriptionBuilderImpl {
};
var DbConnectionBuilder = class extends __DbConnectionBuilder {
};
var DbConnection = class _DbConnection extends __DbConnectionImpl {
  constructor(config) {
    super(config);
    this.db = __withTableAccessorAliases(this.db);
  }
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = () => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config) => new _DbConnection(config));
  };
  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  subscriptionBuilder = () => {
    return new SubscriptionBuilder(this);
  };
};
export {
  DbConnection,
  DbConnectionBuilder,
  SubscriptionBuilder,
  procedures,
  reducers,
  tables
};
