// Generated by effect-spacetimedb codegen (spacetime 2.6.1, esbuild 0.25.12). DO NOT EDIT.
// index.ts
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  table as __table
} from "spacetimedb";

// emit_presence_reducer.ts
import {
  t as __t2
} from "spacetimedb";

// types.ts
import {
  t as __t
} from "spacetimedb";
var AllThings = __t.object("AllThings", {});
var AllUsers = __t.object("AllUsers", {});
var AllUsersQuery = __t.object("AllUsersQuery", {});
var AuditLog = __t.object("AuditLog", {
  id: __t.u64(),
  get kind() {
    return EffectSpacetimeDbEnum1534687482507768812807638219320528948671;
  },
  subject: __t.string()
});
var EffectSpacetimeDbEnum0031112371198784746010532026326169871055 = __t.enum("EffectSpacetimeDbEnum0031112371198784746010532026326169871055", {
  Reducer: __t.unit(),
  Procedure: __t.unit()
});
var EffectSpacetimeDbEnum0077559484257204371700884911820393236990 = __t.enum("EffectSpacetimeDbEnum0077559484257204371700884911820393236990", {
  Joined: __t.unit(),
  Left: __t.unit()
});
var EffectSpacetimeDbEnum1534687482507768812807638219320528948671 = __t.enum("EffectSpacetimeDbEnum1534687482507768812807638219320528948671", {
  Init: __t.unit(),
  Connected: __t.unit(),
  Disconnected: __t.unit()
});
var MembershipView = __t.object("MembershipView", {
  tenantId: __t.string(),
  email: __t.string(),
  note: __t.string()
});
var NativeRangeEntry = __t.object("NativeRangeEntry", {
  id: __t.u64(),
  owner: __t.identity(),
  happenedAt: __t.timestamp(),
  label: __t.string()
});
var PresenceEvent = __t.object("PresenceEvent", {
  userId: __t.string(),
  get kind() {
    return EffectSpacetimeDbEnum0077559484257204371700884911820393236990;
  }
});
var PrivateAuditLog = __t.object("PrivateAuditLog", {});
var ProcedureSchedule = __t.object("ProcedureSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  note: __t.string()
});
var ReducerSchedule = __t.object("ReducerSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  note: __t.string()
});
var ScheduledResult = __t.object("ScheduledResult", {
  id: __t.u64(),
  get target() {
    return EffectSpacetimeDbEnum0031112371198784746010532026326169871055;
  },
  note: __t.string()
});
var SelfUser = __t.object("SelfUser", {});
var Thing = __t.object("Thing", {
  id: __t.string(),
  label: __t.string(),
  count: __t.u64()
});
var UniqueMembership = __t.object("UniqueMembership", {
  tenantId: __t.string(),
  email: __t.string(),
  note: __t.string()
});
var User = __t.object("User", {
  id: __t.string(),
  name: __t.string()
});

// emit_presence_reducer.ts
var emit_presence_reducer_default = {
  userId: __t2.string(),
  get kind() {
    return EffectSpacetimeDbEnum0077559484257204371700884911820393236990;
  }
};

// membership_insert_strict_reducer.ts
import {
  t as __t3
} from "spacetimedb";
var membership_insert_strict_reducer_default = {
  tenantId: __t3.string(),
  email: __t3.string(),
  note: __t3.string()
};

// membership_upsert_reducer.ts
import {
  t as __t4
} from "spacetimedb";
var membership_upsert_reducer_default = {
  tenantId: __t4.string(),
  email: __t4.string(),
  note: __t4.string()
};

// native_range_clear_reducer.ts
var native_range_clear_reducer_default = {};

// native_range_insert_reducer.ts
import {
  t as __t5
} from "spacetimedb";
var native_range_insert_reducer_default = {
  owner: __t5.identity(),
  happenedAt: __t5.timestamp(),
  label: __t5.string()
};

// probe_async_reducer.ts
var probe_async_reducer_default = {};

// probe_random_reducer.ts
var probe_random_reducer_default = {};

// probe_wall_clock_reducer.ts
var probe_wall_clock_reducer_default = {};

// schedule_interval_reducer_note_reducer.ts
import {
  t as __t6
} from "spacetimedb";
var schedule_interval_reducer_note_reducer_default = {
  note: __t6.string()
};

// schedule_procedure_note_reducer.ts
import {
  t as __t7
} from "spacetimedb";
var schedule_procedure_note_reducer_default = {
  note: __t7.string()
};

// schedule_reducer_note_reducer.ts
import {
  t as __t8
} from "spacetimedb";
var schedule_reducer_note_reducer_default = {
  note: __t8.string()
};

// schedule_too_far_reducer.ts
import {
  t as __t9
} from "spacetimedb";
var schedule_too_far_reducer_default = {
  note: __t9.string()
};

// seed_self_user_reducer.ts
import {
  t as __t10
} from "spacetimedb";
var seed_self_user_reducer_default = {
  name: __t10.string()
};

// thing_clear_reducer.ts
var thing_clear_reducer_default = {};

// thing_delete_reducer.ts
import {
  t as __t11
} from "spacetimedb";
var thing_delete_reducer_default = {
  thingId: __t11.string()
};

// thing_force_update_reducer.ts
import {
  t as __t12
} from "spacetimedb";
var thing_force_update_reducer_default = {
  thingId: __t12.string(),
  label: __t12.string(),
  count: __t12.u64()
};

// thing_insert_then_abort_reducer.ts
import {
  t as __t13
} from "spacetimedb";
var thing_insert_then_abort_reducer_default = {
  thingId: __t13.string(),
  label: __t13.string(),
  count: __t13.u64()
};

// thing_insert_twice_atomic_reducer.ts
import {
  t as __t14
} from "spacetimedb";
var thing_insert_twice_atomic_reducer_default = {
  firstThingId: __t14.string(),
  firstLabel: __t14.string(),
  firstCount: __t14.u64(),
  secondThingId: __t14.string(),
  secondLabel: __t14.string(),
  secondCount: __t14.u64()
};

// thing_insert_twice_then_abort_reducer.ts
import {
  t as __t15
} from "spacetimedb";
var thing_insert_twice_then_abort_reducer_default = {
  firstThingId: __t15.string(),
  firstLabel: __t15.string(),
  firstCount: __t15.u64(),
  secondThingId: __t15.string(),
  secondLabel: __t15.string(),
  secondCount: __t15.u64()
};

// thing_noop_reducer.ts
var thing_noop_reducer_default = {};

// thing_panic_reducer.ts
var thing_panic_reducer_default = {};

// thing_set_reducer.ts
import {
  t as __t16
} from "spacetimedb";
var thing_set_reducer_default = {
  thingId: __t16.string(),
  label: __t16.string(),
  count: __t16.u64()
};

// user_require_reducer.ts
import {
  t as __t17
} from "spacetimedb";
var user_require_reducer_default = {
  userId: __t17.string()
};

// user_upsert_reducer.ts
import {
  t as __t18
} from "spacetimedb";
var user_upsert_reducer_default = {
  userId: __t18.string(),
  name: __t18.string()
};

// membership_get_procedure.ts
import {
  t as __t19
} from "spacetimedb";
var params = {
  tenantId: __t19.string(),
  email: __t19.string()
};
var returnType = __t19.option(MembershipView);

// native_range_by_owner_procedure.ts
import {
  t as __t20
} from "spacetimedb";
var params2 = {
  lo: __t20.identity(),
  hi: __t20.identity()
};
var returnType2 = __t20.array(__t20.string());

// native_range_by_timestamp_procedure.ts
import {
  t as __t21
} from "spacetimedb";
var params3 = {
  lo: __t21.timestamp(),
  hi: __t21.timestamp()
};
var returnType3 = __t21.array(__t21.string());

// presence_event_count_procedure.ts
import {
  t as __t22
} from "spacetimedb";
var params4 = {};
var returnType4 = __t22.u64();

// thing_by_count_exact_procedure.ts
import {
  t as __t23
} from "spacetimedb";
var params5 = {
  count: __t23.u64()
};
var returnType5 = __t23.array(Thing);

// thing_by_count_range_procedure.ts
import {
  t as __t24
} from "spacetimedb";
var params6 = {
  lo: __t24.u64(),
  hi: __t24.u64()
};
var returnType6 = __t24.array(Thing);

// thing_count_procedure.ts
import {
  t as __t25
} from "spacetimedb";
var params7 = {};
var returnType7 = __t25.u64();

// thing_get_procedure.ts
import {
  t as __t26
} from "spacetimedb";
var params8 = {
  thingId: __t26.string()
};
var returnType8 = __t26.option(Thing);

// thing_insert_in_tx_then_abort_procedure.ts
import {
  t as __t27
} from "spacetimedb";
var params9 = {
  thingId: __t27.string(),
  label: __t27.string(),
  count: __t27.u64()
};
var returnType9 = __t27.result(__t27.unit(), __t27.string());

// thing_insert_twice_in_tx_procedure.ts
import {
  t as __t28
} from "spacetimedb";
var params10 = {
  firstThingId: __t28.string(),
  firstLabel: __t28.string(),
  firstCount: __t28.u64(),
  secondThingId: __t28.string(),
  secondLabel: __t28.string(),
  secondCount: __t28.u64()
};
var returnType10 = __t28.unit();

// thing_list_procedure.ts
import {
  t as __t29
} from "spacetimedb";
var params11 = {};
var returnType11 = __t29.array(Thing);

// thing_outcome_procedure.ts
import {
  t as __t30
} from "spacetimedb";
var params12 = {
  thingId: __t30.string()
};
var returnType12 = __t30.result(Thing, __t30.string());

// user_get_procedure.ts
import {
  t as __t31
} from "spacetimedb";
var params13 = {
  userId: __t31.string()
};
var returnType13 = __t31.result(__t31.option(User), __t31.string());

// all_things_table.ts
import {
  t as __t32
} from "spacetimedb";
var all_things_table_default = __t32.row({
  id: __t32.string().primaryKey(),
  label: __t32.string(),
  count: __t32.u64()
});

// all_users_table.ts
import {
  t as __t33
} from "spacetimedb";
var all_users_table_default = __t33.row({
  id: __t33.string().primaryKey(),
  name: __t33.string()
});

// all_users_query_table.ts
import {
  t as __t34
} from "spacetimedb";
var all_users_query_table_default = __t34.row({
  id: __t34.string().primaryKey(),
  name: __t34.string()
});

// audit_log_table.ts
import {
  t as __t35
} from "spacetimedb";
var audit_log_table_default = __t35.row({
  id: __t35.u64().primaryKey(),
  get kind() {
    return EffectSpacetimeDbEnum1534687482507768812807638219320528948671;
  },
  subject: __t35.string()
});

// native_range_entry_table.ts
import {
  t as __t36
} from "spacetimedb";
var native_range_entry_table_default = __t36.row({
  id: __t36.u64().primaryKey(),
  owner: __t36.identity(),
  happenedAt: __t36.timestamp().name("happened_at"),
  label: __t36.string()
});

// presence_event_table.ts
import {
  t as __t37
} from "spacetimedb";
var presence_event_table_default = __t37.row({
  userId: __t37.string().name("user_id"),
  get kind() {
    return EffectSpacetimeDbEnum0077559484257204371700884911820393236990;
  }
});

// private_audit_log_table.ts
import {
  t as __t38
} from "spacetimedb";
var private_audit_log_table_default = __t38.row({
  id: __t38.string().primaryKey(),
  name: __t38.string()
});

// procedure_schedule_table.ts
import {
  t as __t39
} from "spacetimedb";
var procedure_schedule_table_default = __t39.row({
  scheduledId: __t39.u64().primaryKey().name("scheduled_id"),
  scheduledAt: __t39.scheduleAt().name("scheduled_at"),
  note: __t39.string()
});

// reducer_schedule_table.ts
import {
  t as __t40
} from "spacetimedb";
var reducer_schedule_table_default = __t40.row({
  scheduledId: __t40.u64().primaryKey().name("scheduled_id"),
  scheduledAt: __t40.scheduleAt().name("scheduled_at"),
  note: __t40.string()
});

// scheduled_result_table.ts
import {
  t as __t41
} from "spacetimedb";
var scheduled_result_table_default = __t41.row({
  id: __t41.u64().primaryKey(),
  get target() {
    return EffectSpacetimeDbEnum0031112371198784746010532026326169871055;
  },
  note: __t41.string()
});

// self_user_table.ts
import {
  t as __t42
} from "spacetimedb";
var self_user_table_default = __t42.row({
  id: __t42.string().primaryKey(),
  name: __t42.string()
});

// thing_table.ts
import {
  t as __t43
} from "spacetimedb";
var thing_table_default = __t43.row({
  id: __t43.string().primaryKey(),
  label: __t43.string(),
  count: __t43.u64()
});

// user_table.ts
import {
  t as __t44
} from "spacetimedb";
var user_table_default = __t44.row({
  id: __t44.string().primaryKey(),
  name: __t44.string()
});

// index.ts
var tablesSchema = __schema({
  auditLog: __table({
    name: "auditLog",
    indexes: [
      { accessor: "id", name: "auditLog_id_idx_btree", algorithm: "btree", columns: [
        "id"
      ] }
    ],
    constraints: [
      { name: "auditLog_id_key", constraint: "unique", columns: ["id"] }
    ]
  }, audit_log_table_default),
  nativeRangeEntry: __table({
    name: "nativeRangeEntry",
    indexes: [
      { accessor: "nativeRangeEntryHappenedAtIdx", name: "nativeRangeEntry_happened_at_idx_btree", algorithm: "btree", columns: [
        "happenedAt"
      ] },
      { accessor: "id", name: "nativeRangeEntry_id_idx_btree", algorithm: "btree", columns: [
        "id"
      ] },
      { accessor: "nativeRangeEntryOwnerIdx", name: "nativeRangeEntry_owner_idx_btree", algorithm: "btree", columns: [
        "owner"
      ] }
    ],
    constraints: [
      { name: "nativeRangeEntry_id_key", constraint: "unique", columns: ["id"] }
    ]
  }, native_range_entry_table_default),
  presenceEvent: __table({
    name: "presenceEvent",
    indexes: [],
    constraints: [],
    event: true
  }, presence_event_table_default),
  procedureSchedule: __table({
    name: "procedureSchedule",
    indexes: [
      { accessor: "scheduledId", name: "procedureSchedule_scheduled_id_idx_btree", algorithm: "btree", columns: [
        "scheduledId"
      ] }
    ],
    constraints: [
      { name: "procedureSchedule_scheduled_id_key", constraint: "unique", columns: ["scheduledId"] }
    ]
  }, procedure_schedule_table_default),
  reducerSchedule: __table({
    name: "reducerSchedule",
    indexes: [
      { accessor: "scheduledId", name: "reducerSchedule_scheduled_id_idx_btree", algorithm: "btree", columns: [
        "scheduledId"
      ] }
    ],
    constraints: [
      { name: "reducerSchedule_scheduled_id_key", constraint: "unique", columns: ["scheduledId"] }
    ]
  }, reducer_schedule_table_default),
  scheduledResult: __table({
    name: "scheduledResult",
    indexes: [
      { accessor: "id", name: "scheduledResult_id_idx_btree", algorithm: "btree", columns: [
        "id"
      ] }
    ],
    constraints: [
      { name: "scheduledResult_id_key", constraint: "unique", columns: ["id"] }
    ]
  }, scheduled_result_table_default),
  thing: __table({
    name: "thing",
    indexes: [
      { accessor: "thingCountIdx", name: "thing_count_idx_btree", algorithm: "btree", columns: [
        "count"
      ] },
      { accessor: "id", name: "thing_id_idx_btree", algorithm: "btree", columns: [
        "id"
      ] }
    ],
    constraints: [
      { name: "thing_id_key", constraint: "unique", columns: ["id"] }
    ]
  }, thing_table_default),
  user: __table({
    name: "user",
    indexes: [
      { accessor: "id", name: "user_id_idx_btree", algorithm: "btree", columns: [
        "id"
      ] }
    ],
    constraints: [
      { name: "user_id_key", constraint: "unique", columns: ["id"] }
    ]
  }, user_table_default),
  all_things: __table({
    name: "all_things",
    indexes: [],
    constraints: []
  }, all_things_table_default),
  all_users: __table({
    name: "all_users",
    indexes: [],
    constraints: []
  }, all_users_table_default),
  all_users_query: __table({
    name: "all_users_query",
    indexes: [],
    constraints: []
  }, all_users_query_table_default),
  private_audit_log: __table({
    name: "private_audit_log",
    indexes: [],
    constraints: []
  }, private_audit_log_table_default),
  self_user: __table({
    name: "self_user",
    indexes: [],
    constraints: []
  }, self_user_table_default)
});
var reducersSchema = __reducers(
  __reducerSchema("emit_presence", emit_presence_reducer_default),
  __reducerSchema("membership_insert_strict", membership_insert_strict_reducer_default),
  __reducerSchema("membership_upsert", membership_upsert_reducer_default),
  __reducerSchema("native_range_clear", native_range_clear_reducer_default),
  __reducerSchema("native_range_insert", native_range_insert_reducer_default),
  __reducerSchema("probe_async", probe_async_reducer_default),
  __reducerSchema("probe_random", probe_random_reducer_default),
  __reducerSchema("probe_wall_clock", probe_wall_clock_reducer_default),
  __reducerSchema("schedule_interval_reducer_note", schedule_interval_reducer_note_reducer_default),
  __reducerSchema("schedule_procedure_note", schedule_procedure_note_reducer_default),
  __reducerSchema("schedule_reducer_note", schedule_reducer_note_reducer_default),
  __reducerSchema("schedule_too_far", schedule_too_far_reducer_default),
  __reducerSchema("seed_self_user", seed_self_user_reducer_default),
  __reducerSchema("thing_clear", thing_clear_reducer_default),
  __reducerSchema("thing_delete", thing_delete_reducer_default),
  __reducerSchema("thing_force_update", thing_force_update_reducer_default),
  __reducerSchema("thing_insert_then_abort", thing_insert_then_abort_reducer_default),
  __reducerSchema("thing_insert_twice_atomic", thing_insert_twice_atomic_reducer_default),
  __reducerSchema("thing_insert_twice_then_abort", thing_insert_twice_then_abort_reducer_default),
  __reducerSchema("thing_noop", thing_noop_reducer_default),
  __reducerSchema("thing_panic", thing_panic_reducer_default),
  __reducerSchema("thing_set", thing_set_reducer_default),
  __reducerSchema("user_require", user_require_reducer_default),
  __reducerSchema("user_upsert", user_upsert_reducer_default)
);
var proceduresSchema = __procedures(
  __procedureSchema("membership_get", params, returnType),
  __procedureSchema("native_range_by_owner", params2, returnType2),
  __procedureSchema("native_range_by_timestamp", params3, returnType3),
  __procedureSchema("presence_event_count", params4, returnType4),
  __procedureSchema("thing_by_count_exact", params5, returnType5),
  __procedureSchema("thing_by_count_range", params6, returnType6),
  __procedureSchema("thing_count", params7, returnType7),
  __procedureSchema("thing_get", params8, returnType8),
  __procedureSchema("thing_insert_in_tx_then_abort", params9, returnType9),
  __procedureSchema("thing_insert_twice_in_tx", params10, returnType10),
  __procedureSchema("thing_list", params11, returnType11),
  __procedureSchema("thing_outcome", params12, returnType12),
  __procedureSchema("user_get", params13, returnType13)
);
var REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.6.1"
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema
};
var tables = __makeQueryBuilder(tablesSchema.schemaType);
var reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);
var procedures = __convertToAccessorMap(proceduresSchema.procedures);
var SubscriptionBuilder = class extends __SubscriptionBuilderImpl {
};
var DbConnectionBuilder = class extends __DbConnectionBuilder {
};
var DbConnection = class _DbConnection extends __DbConnectionImpl {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = () => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config) => new _DbConnection(config));
  };
  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  subscriptionBuilder = () => {
    return new SubscriptionBuilder(this);
  };
};
export {
  DbConnection,
  DbConnectionBuilder,
  SubscriptionBuilder,
  procedures,
  reducers,
  tables
};
