// Generated by effect-spacetimedb codegen (spacetime 2.6.1, esbuild 0.25.12). DO NOT EDIT.
import type { GeneratedConnectionClassLike } from "effect-spacetimedb/client"

export declare const DbConnection: GeneratedConnectionClassLike
